use_frameworks!

# Need one pod
pod 'Forgeries'

target 'BootstrapTests' do
  pod 'Quick', git: 'https://github.com/Quick/Quick.git'
  pod 'Nimble', git: 'https://github.com/Quick/Nimble.git'
  pod 'FBSnapshotTestCase', git: 'https://github.com/facebook/ios-snapshot-test-case.git'

  pod 'Nimble-Snapshots', :path => "../"
end
