use_frameworks!

# Need one pod
pod 'Forgeries'

target 'BootstrapTests' do
  # Waiting on 9.3 support to be released
  pod 'Quick', git: 'https://github.com/Quick/Quick.git'
  pod 'Nimble', git: 'https://github.com/Quick/Nimble.git'

  pod 'Nimble-Snapshots/DynamicType', :path => "../"
end

