use_frameworks!

# Need one pod
pod 'Forgeries'

target 'BootstrapTests' do
  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase', git: 'https://github.com/facebook/ios-snapshot-test-case.git'

  pod 'Nimble-Snapshots', :path => "../"
end
