opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - sorted_imports
  - switch_case_on_newline
  - redundant_nil_coalescing

excluded:
  - Bootstrap/Pods