name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.3.1

    - name: Lint
      run: |
            set -o pipefail
            swiftlint
      
    - name: Build iOS
      run: make build-ios
