name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.3.1
        
    - name: Bundle install
      run: bundle install
      
    - name: Lint
      run: |
            set -o pipefail
            swiftlint
      
    - name: Build iOS
      run: bundle exec rake build:package:iOS
